<# Generate System report with name, disk, CPU, RAM, DomainJoin stat, Network ping status in HTML
Author - Prasant Chettri #>
# PluralSight Powershell HTML and CBE nugget youtube references and tech forums (https://community.spiceworks.com/topic/2313144-add-a-variable-to-an-html-report-with-table-view) for header block
# Ref1 https://devblogs.microsoft.com/scripting/working-with-html-fragments-and-files/
# Ref2 https://community.spiceworks.com/topic/2313144-add-a-variable-to-an-html-report-with-table-view

Set-Location $PSScriptRoot
# Creating label
$form = New-Object Windows.Forms.Form


$form.width = 500
$form.height = 300
$form.text = "Input to test network ping"
$form.BackColor="Blue"

# create label 
$label = new-object Windows.Forms.Label
$label.text = "Paste the computername to ping"

$label.Width=220
$label.height=20

$label.Location = New-Object Drawing.Point 100,30
$label.Backcolor='Orange'

$form.controls.add($label)
$form.ShowDialog

# create a text box
$textfield = new-object Windows.Forms.TextBox
$textfield.location = New-object Drawing.Point 100,80
$textfield.Width=220
$textfield.height=20

# Create command buttons
$btn = New-Object Windows.Forms.Button
$btn.location = New-Object Drawing.Point 100,120
$btn.Width=200
$btn.height=40
$btn.BackColor="Orange"
$btn.Text="OK";


 $eventHandler = [System.EventHandler]{
         $form.Close();
 };

 $btn.Add_Click($eventHandler) ;
 $DestC=$textfield.Text
<#$btn.Add_Click(
{
$DestC=$textfield.Text;
Write-host $DestC
[System.Windows.Forms.MessageBox]::show("Details acccepted.", "Admin Says")
$form.close()
}
)#>
$DestC=$textfield.Text
$form.controls.add($label)
$form.controls.add($textfield)
$form.controls.add($btn)
$form.ShowDialog()



#Splt expresson for string 


$userW = whoami
$dom, $UserN = $userW.split("\")
$usern 
$CurrentDate = Get-date -Format MM/dd/yyyy
$CurrentDate
$computerName = hostname
$DestC=$textfield.Text
$UserPath = "$($env:USERPROFILE)\Documents\$computerName.html"  # Create a file with the host name on current user documents path
$comp1 = hostname

#First HTML

$head3 = @"
<style>
h1, h5, h3, th { text-align: center; }
table { margin: auto; font-family: Segoe UI; box-shadow: 10px 10px 5px #888; border: thin ridge grey; }
th { background: #00463; color: #fff; max-width: 400px; padding, 5px 10px; }
td { font-size: 11px; padding: 5px 20px; color: #000; }
tr { background: #b8d1f3;  }
tr:nth-child(even) {background: #dae5f4; }
tr:nth-child(even) {background: #b8d1f3; }
</style>
"@


$body = "<h3>Test report summary for $comp1. This report was generated by $usern on $currentdate</h3>" 
 Get-ComputerInfo | select CsName| ConvertTo-Html -Property name -head $head3 -body $body | out-file $userpath


#Style Sheet for HTML Report including Title
$header = @"
<style>
      h1 {

        font-family: Arial, Helvetica, sans-serif;
        color: #e68a00;
        font-size: 28px;

    }

    h2 {

        font-family: Arial, Helvetica, sans-serif;
        color: #000099;
        font-size: 16px;

    }

   table {
		font-size: 12px;
		border: 0px; 
		font-family: Arial, Helvetica, sans-serif;
	} 
	
    td {
		padding: 4px;
		margin: 0px;
		border: 0;
	}
	
    th {
        background: #395870;
        background: linear-gradient(#49708f, #293f50);
        color: #fff;
        font-size: 11px;
        text-transform: uppercase;
        padding: 10px 15px;
        vertical-align: middle;
	}

    tbody tr:nth-child(even) {
        background: #f0f0f2;
    }

        CreationDate {

        font-family: Arial, Helvetica, sans-serif;
        color: #ff3300;
        font-size: 12px;

    }
   
    </style>
"@

#Getting Computer Info
$computerInfo = Get-ComputerInfo | `
    #Selecting what data to show up in report with specifc header
    select-object @{n = 'Computername'; e = { $env:computername } },
@{n = 'OS Version'; e = { $_.WindowsProductName } },
@{n = 'Language'; e = { $_.OsLocale } },
@{n = 'CPU'; e = { $_.CsNumberOfProcessors } } ,
@{n = 'CPUCores'; e = { $_.CsNumberOfLogicalProcessors } } ,
@{n = 'RAM'; e = { [math]::round($_.OsTotalVisibleMemorySize / 1MB, 0) } } | `
    ConvertTo-Html -Fragment

#WindowsOS licensing details

$Licenseinfo= Get-CimInstance SoftwareLicensingProduct | where licensestatus -eq 1  | `
 Select-Object @{n = 'Windows Edition'; e = { $_.name} },
 @{n= 'Windows License Channel'; e = {$_.Description} } ` |
    ConvertTo-html -Fragment

#network test

$networkstat= Test-NetConnection -ComputerName $Destc |`
 Select-Object @{n = 'Network ping  '; e = { $_.PingSucceeded} }| ConvertTo-Html -Fragment

 # Find members of local admin group


 $members = net localgroup administrators

 $localGroup = $members[6..($members.Length-3)]




# Windows domain join status - Validating Domain status and generating HTML statement


$domainSuffix = Get-WmiObject -Namespace root\cimv2 -Class Win32_ComputerSystem | Select Domain

#Heading 
<#$headinfo = [PSCustomObject]@{
"Summary of VM QA test information for $computerName "= " Generated by $usern on $currentdate"
}| ConvertTo-Html -Property "Summary of VM QA test information for $computerName " -Fragment
#>


 $domainStat = (Get-WmiObject -Class Win32_ComputerSystem).PartOfDomain
if ($domainStat -eq $true) 
{

 $DJstat = "$computerName is joined to domain $domainsuffix - $domainstat"
 }
 else{
 $DJstat = "$computerName failed to join domain $domainsuffix  - $domainstat"
 }

 $DJdetail = [PSCustomObject]@{
 'Domain join status' = $DJstat
 } | convertto-html -Property  'Domain join status' -Fragment


#To get the logical disk information first drive letter which has logcal OS value of 3 and shows the remaining drive based on OS disk assignment
$diskInfo = Get-CimInstance Win32_LogicalDisk | `
    Where-Object { $_.DriveType -eq '3' } | `
    #Selecting what data to show up in report with specifc header
    Select-Object `
    DeviceID, @{N = 'Total Size(GB)'; E = { [math]::Round($_.Size / 1GB, 2) } }, @{N = 'Free size(GB)'; E = { [math]::Round($_.Freespace / 1GB) } } | `
    ConvertTo-Html -Fragment



# Validating network status and generating HTML statement
$netstat = Test-NetConnection -ComputerName $DestC |select PingSucceeded 

If ($netstat -eq $True)
{
$netrep =  "The network test was successful - $netstat"
}
else {
$netrep =  "FAILED The network test - $netstat"
}


#ConvertTo-Html requires an object let's create an object with network test status
$netdetail = [PSCustomObject]@{
 'Network Ping status' = $netrep
 } | convertto-html -Property  'Network Ping status' -Fragment # REF https://social.technet.microsoft.com/Forums/windowsserver/en-US/588275ba-1b3a-42af-b59c-20264b25ff99/converttohtml-shows-quotquot-in-html-table-column-header?forum=winserverpowershell
$htmlParams = @{
    Head = $header
    #we use 'Body' parameter instead of 'PostContent'.  'PostContent' is more of a 'footer' area.
    Body = "$computerInfo $diskInfo $Licenseinfo $netdetail $DJdetail $groupsinfo"
    
   
}



#Generate HTML Report
ConvertTo-Html  `
               @htmlParams | Out-File $userpath -append  #-Title "Network ping was successful"

$head2 = @"
<style>
h1, h5, h3, th { text-align: center; }
table { margin: auto; font-family: Segoe UI; box-shadow: 10px 10px 5px #888; border: thin ridge grey; }
th { background: #00463; color: #fff; max-width: 400px; padding, 5px 10px; }
td { font-size: 11px; padding: 5px 20px; color: #000; }
tr { background: #b8d1f3;  }
tr:nth-child(even) {background: #dae5f4; }
tr:nth-child(even) {background: #b8d1f3; }
</style>
"@

<#$body = "<h3>List of computer groups</h3>"
Get-LocalGroup | select name | ConvertTo-Html -Property name -head $head2 -body $body | out-file $userpath -Append#>
$body = "<h3>List of Remote Desktop Users</h3>"
Get-LocalGroupMember -name "Remote Desktop Users" | select ObjectClass, name, PrincipalSource | ConvertTo-Html -Property ObjectClass, name, PrincipalSource -head $head2 -body $body | out-file $userpath -Append
 Get-WMIObject Win32_Group -filter "name='Administrators'"


$body = "<h3>Members of local admin groups</h3>"
Get-LocalGroupMember -SID "S-1-5-32-544" | select ObjectClass, name, PrincipalSource | ConvertTo-Html -Property ObjectClass, name, PrincipalSource -head $head2 -body $body | out-file $userpath -Append
 Get-WMIObject Win32_Group -filter "name='Administrators'"

#Opens the resulting report.html file using the system's default HTML viewer.
$fP="file://"
$fpath= $fp+$userpath
# Invoke-Item $UserPath (use this command if the Invoke command is supported
Start $fpath  # user this command if invoke cmdlet is blocked

#Copy to Blog SAS URL and container location - ISSUE change content type to fix browsing


$fname = (get-item $userpath).name 
$uri = "https://pcblob.core.windows.net/report/$($fname)?si=report&spr=https&sv=2021-06-08&sr=c&sig=XiFUSwxUblRn%2FAbCEKTiXjkNyvByLUPyr8L4jxMJanA%3D"
$headers = @{
    'x-ms-blob-type' = 'BlockBlob'
}

